final products = [
  {
    'title': 'Classic Canvas Sneakers',
    'price': '₹4,388',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes9.png',
    'category': 'women',
  },
  {
    'title': 'Ultra Boost 21',
    'price': '₹7,055',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes2.png',
    'category': 'men',
  },
  {
    'title': 'Slip-On Canvas Shoes',
    'price': '₹3,320',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes4.png',
    'category': 'men',
  },
  {
    'title': 'High-Top Retro Sneakers ',
    'price': '₹7,862',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes1.png',
    'category': 'women',
  },
  {
    'title': 'High Top Basketball Shoes',
    'price': '₹9,130',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes5.png',
    'category': 'men',
  },
  {
    'title': 'FusionWalk Sneakers',
    'price': '₹6,388',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men-shoes.png',
    'category': 'men',
  },
  {
    'title': 'FusionWalk Sneakers',
    'price': '₹6,388',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes3.png',
    'category': 'women',
  },
  {
    'title': 'Retro Runner',
    'price': '₹6,985',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes3.png',
    'category': 'men',
  },
  {
    'title': 'Velcro Sneakers',
    'price': '₹2,167',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes4.png',
    'category': 'women',
  },
  {
    'title': 'Chic Ankle Boots',
    'price': '₹9,020',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes5.png',
    'category': 'women',
  },
  {
    'title': 'Stylish Loafers',
    'price': '₹5,810',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes7.png',
    'category': 'men',
  },
  {
    'title': 'Air Max 2023',
    'price': ' ₹9,960',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes1.png',
    'category': 'men',
  },
  {
    'title': 'AdventureQuest Boots',
    'price': '₹7,000',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/women_shoes6.png',
    'category': 'women',
  },
  {
    'title': 'Lightweight Running Shoes',
    'price': '₹2,357',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes6.png',
    'category': 'men',
  },
  {
    'title': 'Sporty Mesh Trainers',
    'price': '₹3,320',
    'sizes': ['4', '5', '6', '7', '8', '9'],
    'imageUrl': 'images/men_shoes8.png',
    'category': 'men',
  },
];
